export enum AppActionType {
  ACTION_SET_CODELIST = 'ACTION_SET_CODELIST', //码值设置
  ACTION_SET_SIDEBARSTATUS = 'ACTION_SET_SIDEBARSTATUS', //侧边菜单导航显隐设置
  ACTION_SET_ACTIVEMENU = 'ACTION_SET_ACTIVEMENU', //设置当前激活菜单
}
